config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"

  resource :session
  resources :passwords, param: :token

  resources :posts, param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/publishable.rb
module Publishable
  extend ActiveSupport::Concern

  included do
    default_scope { order(published_at: :desc) }

    # Scopes
    scope :scheduled, -> { where.not(published_at: nil).where("published_at > ?", Date.today) }
    scope :published, -> { where.not(published_at: nil).where("published_at <= ?", Date.today) }
    scope :drafts, -> { where(published_at: nil) }

    def published?
      published_at.present? && published_at <= Date.today
    end

    def scheduled?
      published_at.present? && published_at > Date.today
    end

    def draft?
      !published?
    end
  end
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
     before_validation :sluggify_title, on: :create

     validates :slug, presence: true, uniqueness: true, length: { minimum: 2 }

    # For nice path helpers
    def to_param
      slug
    end

    private

    def sluggify_title
      self.slug = title.parameterize if title.present?
    end
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/post.rb
class Post < ApplicationRecord
  include Sluggable
  include Publishable

  has_rich_text :content

  ALLOWED_CATEGORIES = %w[project written small ddr misc].freeze

  validates :title, presence: true
  validates :description, presence: true

  validates :author, presence: true

  validates :category, inclusion: { in: ALLOWED_CATEGORIES }

  validates :redirect_link, allow_blank: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]), message: "must be a valid URL" }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  allow_unauthenticated_access only: %i[ index ]

  def index
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: %i[ show ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    unless request.referer&.include?(edit_post_path(@post))
      redirect_to @post.redirect_link, status: :moved_permanently, allow_other_host: true if @post.redirect_link.present?
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(slug: params.expect(:slug))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :description, :author, :redirect_link, :category, :content, :published_at ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/landing/_about.html.erb
<div class="container">
  <h2 class="text-neutral-400 font-light pb-2 sm:pb-0">About me</h2>
  <div class="content flex flex-col">
    <p>
      <a href="https://read.cv/isbonora" target="_blank" style="">Isaac Bonora</a> is an <a href="https://wikipedia.org/wiki/Industrial_design" target="_blank">Industrial Designer</a>     and programmer based in Munich, Germany. In 2023 he graduated with first-class honours in     Industrial Design at     <a href="https://wikipedia.org/wiki/Queensland_University_of_Technology" target="_blank">Queensland University of Technology</a>     with a strong interest in solving users’ problems with design thinking. He is currently a designer at <a href="https://idealworks.com/" target="_blank">Idealworks</a>, a     <a href="https://wikipedia.org/wiki/BMW" target="_blank">BMW Group</a> and <a href="https://www.agile-robots.com/en/" target="_blank">Agile Robots</a> company, applying <a href="https://www.interaction-design.org/literature/topics/human-centered-design" target="blank">human-centered design</a> techniques to support teams internally with web-based solutions to improve user satisfaction.<!---->
    <p>
  </div>
</div>

app/views/landing/_location.html.erb
<div class="container" data-controller="location">
  <h2 class="text-neutral-400 font-light pb-2 sm:pb-0">Where</h2>
  <div class=" w-full">
   <div data-location-target="map" class="h-[300px]"></div>
  </div>
</div>

app/views/landing/_posts.html.erb
<% %w[project written small ddr misc].each do |category| %>
    <% if Post.where(category: category).published.present? %>
    <div class="container">
        <% if authenticated? %>
        <%= link_to posts_path do |link| %>
            <h2 class="text-neutral-400 font-light pb-2 sm:pb-0"><%= category.titleize.pluralize %></h2>
        <% end %>
        <% else %>
            <h2 class="text-neutral-400 font-light pb-2 sm:pb-0"><%= category.titleize.pluralize %></h2>
        <% end %>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <% Post.where(category: category).published.each do |post| %>
            <div class="bg-neutral-100 px-4 py-2">
                <%= link_to post_url post do |link|%>
                    <div class="flex flex-row justify-between items-center">
                        <span class="text-md font-bold text-black"><%= post.title %></span>
                        <span class="text-sm text-gray-500"><%= post.published_at.strftime("%Y") %></span>
                    </div>
                    <p class="text-sm text-gray-500"><%= post.description %></p>
                <% end %>
                </div>
            <% end %>
        </div>
    </div>
    <% end %>
<% end %>

app/views/landing/index.html.erb
<div class="my-12 flex flex-col gap-8">

    <%= render partial: "about" %>

    <%= render partial: "posts" %>
    <%= render partial: "location" %>

</div>

app/views/layouts/_header.html.erb
<div class="container">
        <% if authenticated? %>
    <h2 class="opacity-25 hover:opacity-100">
            <%= form_with url: session_path, method: :delete, class: "inline" do %>
                <button type="submit" class="text-red-500 hover:underline cursor-pointer">Logout</button>
            <% end %>
    </h2>
        <% end %>
    <div class="flex flex-row items-center gap-2">
        <%= image_tag "headshot.jpeg", alt: "Logo", class: "h-18 w-18 mr-2 rounded-full" %>
        <div class="flex flex-col">
            <%= link_to "Isaac Bonora", root_path, class: "text-2xl font-light text-gray-900" %>
            <span class="text-sm">Industrial Designer in Munich, DE.</span>
            <div class="flex gap-2 mt-1">
                <%= link_to "linkedin", "https://www.linkedin.com/in/isbonora/", class:"bg-neutral-200 text-xs px-1 py-0.5", target: "_blank" %>
                <%= link_to "github", "https://github.com/isbonora", class:"bg-neutral-200 text-xs px-1 py-0.5", target: "_blank" %>
                <%= link_to "instagram", "https://www.instagram.com/isbonora.design/", class:"bg-neutral-200 text-xs px-1 py-0.5", target: "_blank" %>
                <%= link_to "cv", "https://docs.google.com/spreadsheets/d/1r6yXxNRnAWpy8E9hcNJVzMdt4hY5n5QvVtYqNK--Hhw/edit?gid=0#gid=0", class:"bg-neutral-200 text-xs px-1 py-0.5", target: "_blank" %>
            </div>
        </div>
    </div>
</div>  

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Isaac Bonora" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/favicon-96x96.png" type="image/png">
    <link rel="icon" href="/favicon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= yield :body_class %>">
    <main class="container mx-auto mt-28 mb-14 w-full sm:w-[800px] px-1 sm:px-5 flex flex-col">
      <%= render partial: "layouts/header"%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="list-disc ml-6">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 


  <div class="grid grid-cols-2  gap-4">
  <div class="col-span-2">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:title].none?, "border-red-400 focus:outline-red-600": post.errors[:title].any?}] %>
  </div>

  <div class="col-span-2">
    <%= form.label :description %>
    <%= form.text_field :description, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:description].none?, "border-red-400 focus:outline-red-600": post.errors[:description].any?}] %>
  </div>

  <div class="">
    <%= form.label :author %>
    <%= form.text_field :author, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:author].none?, "border-red-400 focus:outline-red-600": post.errors[:author].any?}] %>
  </div>

  <div class="">
    <%= form.label :published_at %>
    <%= form.date_field :published_at, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:author].none?, "border-red-400 focus:outline-red-600": post.errors[:author].any?}] %>
  </div>

  <div class="">
    <%= form.label :category %>
    <%= form.select :category, ["project", "written", "small", "misc", "ddr"], {}, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:status].none?, "border-red-400 focus:outline-red-600": post.errors[:status].any?}] %>
  </div>

  <div class="">
    <%= form.label :redirect_link %>
    <%= form.text_field :redirect_link, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:category].none?, "border-red-400 focus:outline-red-600": post.errors[:category].any?}] %>
  </div>

  <div class="">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": post.errors[:category].none?, "border-red-400 focus:outline-red-600": post.errors[:category].any?}] %>
  </div>


    <div class="field col-span-2">
    <%= form.label :content %>
    <%= form.rich_textarea :content %>
  </div>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="flex flex-col gap-3 mb-5 relative">
  
  <div class="bg-neutral-100 px-4 py-2">
    
    <div class=" flex flex-col gap-1">
      <h1 class="text-2xl font-bold text-gray-900">
        <%= post.title %>
      </h1>
    </div>

    <div class="flex flex-row justify-between items-center">
      <p class="text-sm text-gray-500"><%= post.description %></p>
   
      
    </div>
   <% if post.published? %>
      <span class="text-sm text-gray-500"><%= post.published_at.strftime("%Y") %></span>
      <% elsif post.scheduled? %>
      <span class="text-sm text-gray-500">Scheduled <%= post.published_at %></span>
      <% else %>
      <span class="text-sm text-red-500">DRAFT</span>
      <% end %>
        <% if post.redirect_link.present? %>
    <div class=" text-red-500">
       <%= link_to "Redirected", post.redirect_link %>
      </div>
  <% end %>
  </div>



  <% unless action_name == "index" %>
    <div class="bg-neutral-100 px-4 py-2 w-full">
      <%= post.content %>
    </div>
  <% end %>

</div>

app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<div class="w-full mt-12">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to "New post", new_post_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render post %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", post, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_post_path(post), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", post, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No posts found.</p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<div class=" w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", posts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<% content_for :title, "#{@post.title} || Isaac Bonora" %>

<div class="w-full mt-12">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% if authenticated? %>
    <div class="opacity-25 hover:opacity-100 sm:-left-36 sm:absolute flex flex-col ">
      <%= link_to "Edit this post", edit_post_path(@post), class: "" %>
      <%= link_to "Back to posts", posts_path, class: "" %>
      <%= button_to "Destroy this post", @post, method: :delete, form_class: "", class: "cursor-pointer text-red-600 hover:underline", data: { turbo_confirm: "Are you sure?" } %>
    </div>
  <% end %>

  <%= render @post %>

</div>